#!/bin/sh
#
# @name Gazebo x500 vision
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_vision}

. ${R}etc/init.d-posix/airframes/4001_gz_x500

# Standart GPS Kalkış ve İsteğe Bağlı Hibrit Görsel Odometri + Kumandadan Anında ARM
# GPS TAMAMEN DEVRE DIŞI (İç mekan GPS-Denied modu)
param set SIM_GZ_EN_GPS 0
param set SIM_GZ_EN_ODOM 0
param set SYS_FAILURE_EN 0
param set EKF2_GPS_CTRL 0
param set EKF2_EV_CTRL 15
param set EKF2_HGT_REF 3
param set EKF2_MAG_TYPE 5
param set EKF2_MAG_CHECK 0
param set NAV_RCL_ACT 7
param set COM_RCL_EX_T 0.5
param set COM_RCL_EXCEPT 7
param set NAV_DLL_ACT 0
param set COM_ARM_WO_GPS 1
param set COM_RC_IN_MODE 1
param set COM_FLTMODE_BOOT 2
param set EKF2_GPS_CHECK 0
param set MIS_TAKEOFF_ALT 1.5
param set COM_ARM_MAG_STR 0
param set COM_ARM_MAG_ANG -1
param set CBRK_IO_SAFETY 22027
param set CBRK_USB_CHK 197848
param set CBRK_SUPPLY_CHK 894281
param set COM_ARM_MIS_REQ 0
param set COM_ARM_CHK_ESCS 0

# Görünmez Kalkan / Çarpışma Önleme (Collision Prevention - 360 Lidar Kalkanı)
param set CP_DIST 0.6
param set CP_DELAY 0.2
param set CP_GUIDE_ANG 30.0
param set CP_GO_NO_DATA 0
